name: CI
on:
  - pull_request
  - push
jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    needs: csfix
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
    name: Nasm Test on ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Nasm
        uses: ilammy/setup-nasm@v1

      - name: Build
        run: cd src && make
